### ISSUE TITLE
Allow expressions for Constant values

### ISSUE THREAD

**Issue by rdaly525** [leonardt/verilogAST-cpp#4]
We need the ability to support expressions for slices, indices, instance parameter values, etc...
This allows us to declare ports like:

`input [width-1:0] in0`

**Comment by rdaly525** [comment]
One option is to separate the notion of constant expressions from expressions on wires/registers. This would require redefining all the valid constant expression operators, but in the end might be easier to deal with. @leonardt, thoughts?

**Comment by rdaly525** [comment]
Just confirmed that verilator accepts all operators for constant expressions on parameters. Even the weird ones like 'or reduce':

Totally valid:
`input [(|width):0] in0`

**Comment by leonardt** [comment]
Closed by https://github.com/leonardt/verilogAST-cpp/blob/master/tests/parameterized_module.cpp
